### PR TITLE
Updates directory structure to Go standard.

### PR DESCRIPTION
**Pull request by d-Pixie**
Moves source files into `src/eventsource-server` to allow for simply adding the
root of the checkedout source to the `GOPATH` environment variable for building
instead of requiering the folder structure on the local machine to be set up a
special way for Go.

Removes Makefile, the Go project page clearly state that any Makefile is not
needed for Go and that their inclusion is a failure of Go :)
https://golang.org/doc/articles/go_command.html second paragraph under
"Motivation". Also the Makefile was not used in the documented build anyway.

Updates the README to include new instructions for building the project.

### CODE REVIEW

**Comment by besen** [comment]
Do you have a source that says the src/ folder is a best practice? I don't think this is correct. 

https://github.com/golang/go/wiki/GOPATH#repository-integration-and-creating-go-gettable-projects
https://github.com/golang/go/wiki/GOPATH#use-a-single-gopath

> Even though the GOPATH may be a list of directories, it is generally correct and sufficient to use a single GOPATH for all Go code on your machine. Since all packages retrieved with "go get" have a unique URL (and thus a unique path on disk), having more than one GOPATH is almost never necessary when building with the Go tool.

From my understanding, `go` tools act on a workspace, so a src/ folder can have multiple projects.

**Comment by luizbranco** [comment]
The folder changes are wrong and unnecessary. If you follow the official documents pointed by Tom in the docs. You can also check any top go app on github (https://github.com/search?l=go&q=stars%3A%3E1&s=stars&type=Repositories) and none uses this folder structure.

Also, if you are using `git clone` to get the repo instead of `go get` you are doing it wrong.

The `Makefile` is used to compile the binary to multiple platforms at once. Of course, you can run both commands by hand.

**Comment by d-Pixie** [comment]
@besen Depends :) If you want to be able to keep your code separated by project. It's hard to do if all you have is the global namespace of one `/src`directory.

@luizbranco Hi Luiz :) I have been trying to get you on Skype for a while. Think we could hook up on some chat and talk a bit about Require.js? About this PR: Git clone should be totally ok, considering the Go team uses it in it's documentation examples (https://golang.org/doc/articles/go_command.html under "Go's conventions" for example). The tradeoff is that you need to make sure the code is in you `GOPATH` yourself.

So, maybe we can get to the root question here, since I do get what both of you are saying but none of your comments actually address the problem I was trying to solve with the PR :) I'd like to have my Go sources separated, not all in one place. Normally I have a top level directory where I keep all the source related to a project, I have a `~/replay` directory for example.

With Go and the normal approach I would get it all in the same place. With this PR I don't. I get that my solution might be a bad idea since it breaks other things with the Go ecosystem (I read up a bit more). But there must be some way to do both besides using symlinks? Suggestions?

**Comment by besen** [comment]
I haven't used this yet, but it mentions 'managing GOPATH', so maybe it solves the problem: https://github.com/moovweb/gvm

**Comment by luizbranco** [comment]
@d-Pixie I've sent my contact info on my last email to RP. You can also mention me on a commit/PR while I still have access. I don't use skype.

Since this is a problem on how you want to setup your env - and not specific to this repo - you could do something like: 

```
mkdir -p ~/replay/go
export GOPATH=~/replay/go
go get github.com/replaygaming/go-eventsource
go build github.com/replaygaming/go-eventsource
~/replay/go/bin/go-eventsource
```

Or you could ask in the go mailling list or on the #go-nuts on freenode a better way.

**Comment by d-Pixie** [comment]
I can live with either one Go-root or switching it once in a while :) Sorry for wasting your time @besen and @luizbranco ...

**Pull request closed without merging**
